debug: true
local: false
restapi:
  probe_host: "0.0.0.0"
  probe_port: "18000"
  graphql_host: "op-be-graphql"
  graphql_port: "18080"
grpc:
  logger_host: "op-be-logging"
  logger_port: "18080"
  user_host: "op-be-user"
  user_port: "18080"